### ISSUE TITLE
#DISSECT# 搜索结果为空

### ISSUE THREAD

**Issue by vincentweiss** [CNGB-DC/InstituteDBs#2]
搜索结果为空

![1](https://cloud.githubusercontent.com/assets/3094890/19714575/f599106a-9b81-11e6-8dd6-d944d812f2f4.png)
![2](https://cloud.githubusercontent.com/assets/3094890/19714578/fb80aa38-9b81-11e6-9c87-8c4f14457c53.png)

**Comment by duwensi** [comment]
Example updated. There will still be blank table if the API always raise time out.

**Comment by vincentweiss** [comment]
You can ask for some more search examples which can work smoothly .
